#! /bin/bash

echo -e '||====================||'
echo -e '||    Install Menu    ||'
echo -e '||====================||'

echo -e 'What would you like to do?'
echo -e ' '
echo -e 'Full Install...................1'
echo -e 'Base Package Install..............2'
echo -e 'Doom Emacs Install...............3'
echo -e 'Rust Install...............3'
echo -e 'Rust Install...............3'
echo -e ''
echo -e 'Exit.......................0'
echo ''

read input

case "$input" in
    0) exit
       ;;
    1)  clear
        source $HOME/GitRepos/scripts/
        ;;

    2)  clear
        source $HOME/GitRepos/scripts/installer_scripts/install
        ;;

    3)  clear
        source $HOME/GitRepos/scripts/update_scripts/up
        ;;

    *)
        echo 'You Selected the Wrong Selection'
        source $HOME/GitRepos/scripts/main
esac
