#! /bin/bash
echo '==> Initializing System wide Update'

cd

echo 'Starting With Systems Update'
sudo dnf update

echo '==> updating Rust and Cargo'
rustup update
cargo update

echo '==> Updating Node'
npm install -g npm

echo '==> Updating GitRepo Directory'
~/GitRepos/scripts/git_scripts/repo_directory_update.sh

echo '==> Updating Complete'
